#!/usr/bin/env python
"""Script to fix corrupted sections in routes/admin.py"""

input_file = r'c:\New folder\New folder\Chrome Downloads\New folder\Portfolio Site\routes\admin.py'
output_file = r'c:\New folder\New folder\Chrome Downloads\New folder\Portfolio Site\routes\admin_fixed.py'

# Read the file
with open(input_file, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Convert to list for easier manipulation
fixed_lines = []

# Keep track of where we are
i = 0
while i < len(lines):
    line_num = i + 1  # 1-indexed
    
    # Fix 1: Lines 180-182 - Missing Projects CRUD, orphaned skills code
    if line_num == 180 and lines[i].startswith('# Projects CRUD'):
        # Replace lines 180-182
        fixed_lines.append('# Projects CRUD\r\n')
        fixed_lines.append('@admin_bp.route(\'/projects\')\r\n')
        fixed_lines.append('@login_required\r\n')
        fixed_lines.append('def projects():\r\n')
        fixed_lines.append('    projects = Project.query.order_by(Project.created_at.desc()).all()\r\n')
        fixed_lines.append('    return render_template(\'admin/projects/index.html\', projects=projects)\r\n')
        fixed_lines.append('\r\n')
        fixed_lines.append('# Skills CRUD\r\n')
        fixed_lines.append('@admin_bp.route(\'/skills\')\r\n')
        fixed_lines.append('@login_required\r\n')
        fixed_lines.append('def skills():\r\n')
        fixed_lines.append('    skills = Skill.query.all()\r\n')
        fixed_lines.append('    return render_template(\'admin/skills/index.html\', skills=skills)\r\n')
        i += 3  # Skip lines 180-182
        continue
    
    # Fix 2: Lines 253-258 - Wrong delete_skill implementation
    elif line_num == 253 and '    db.session.delete(skill)' in lines[i]:
        # Check if this is the corrupted delete_skill section
        if i + 5 < len(lines) and 'Gallery item deleted' in lines[i + 4]:
            fixed_lines.append('    db.session.delete(skill)\r\n')
            fixed_lines.append('    db.session.commit()\r\n')
            fixed_lines.append('    \r\n')
            fixed_lines.append('    flash(\'Skill deleted successfully!\', \'success\')\r\n')
            fixed_lines.append('    return redirect(url_for(\'admin.skills\'))\r\n')
            fixed_lines.append('\r\n')
            fixed_lines.append('# Gallery CRUD\r\n')
            fixed_lines.append('@admin_bp.route(\'/gallery\')\r\n')
            fixed_lines.append('@login_required\r\n')
            fixed_lines.append('def gallery():\r\n')
            fixed_lines.append('    from flask import request\r\n')
            fixed_lines.append('    from models import GalleryCategory\r\n')
            fixed_lines.append('    \r\n')
            fixed_lines.append('    # Base query\r\n')
            fixed_lines.append('    query = Gallery.query\r\n')
            fixed_lines.append('\r\n')
            fixed_lines.append('    # Filters\r\n')
            fixed_lines.append('    category_name = request.args.get(\'category\')\r\n')
            fixed_lines.append('    if category_name:\r\n')
            fixed_lines.append('        # Filter by category name via join\r\n')
            fixed_lines.append('        query = query.join(GalleryCategory).filter(GalleryCategory.name == category_name)\r\n')
            fixed_lines.append('\r\n')
            fixed_lines.append('    search = request.args.get(\'search\')\r\n')
            fixed_lines.append('    if search:\r\n')
            fixed_lines.append('        like = f\"%{search}%\"\r\n')
            fixed_lines.append('        query = query.filter(\r\n')
            fixed_lines.append('            (Gallery.title.ilike(like)) | (Gallery.description.ilike(like))\r\n')
            fixed_lines.append('        )\r\n')
            fixed_lines.append('\r\n')
            fixed_lines.append('    # Sorting\r\n')
            fixed_lines.append('    sort = request.args.get(\'sort\', \'newest\')\r\n')
            fixed_lines.append('    if sort == \'oldest\':\r\n')
            fixed_lines.append('        query = query.order_by(Gallery.created_at.asc())\r\n')
            fixed_lines.append('    elif sort == \'title\':\r\n')
            fixed_lines.append('        query = query.order_by(Gallery.title.asc())\r\n')
            fixed_lines.append('    elif sort == \'category\':\r\n')
            fixed_lines.append('        query = query.join(GalleryCategory).order_by(GalleryCategory.name.asc(), Gallery.created_at.desc())\r\n')
            fixed_lines.append('    else:\r\n')
            fixed_lines.append('        # newest\r\n')
            fixed_lines.append('        query = query.order_by(Gallery.created_at.desc())\r\n')
            fixed_lines.append('\r\n')
            fixed_lines.append('    # Pagination\r\n')
            fixed_lines.append('    page = request.args.get(\'page\', 1, type=int)\r\n')
            fixed_lines.append('    per_page = request.args.get(\'per_page\', 12, type=int)\r\n')
            fixed_lines.append('    pagination = query.paginate(page=page, per_page=per_page, error_out=False)\r\n')
            fixed_lines.append('\r\n')
            fixed_lines.append('    # Categories for filter UI (if needed in template)\r\n')
            fixed_lines.append('    categories = GalleryCategory.query.all()\r\n')
            fixed_lines.append('\r\n')
            fixed_lines.append('    return render_template(\r\n')
            fixed_lines.append('        \'admin/gallery/index.html\',\r\n')
            fixed_lines.append('        gallery=pagination,\r\n')
            fixed_lines.append('        categories=categories\r\n')
            fixed_lines.append('    )\r\n')
            fixed_lines.append('\r\n')
            fixed_lines.append('@admin_bp.route(\'/gallery/new\', methods=[\'GET\', \'POST\'])\r\n')
            fixed_lines.append('@login_required\r\n')
            fixed_lines.append('def new_gallery_item():\r\n')
            fixed_lines.append('    from app import db\r\n')
            fixed_lines.append('    from models import GalleryCategory\r\n')
            fixed_lines.append('    from forms import GalleryForm\r\n')
            fixed_lines.append('    \r\n')
            fixed_lines.append('    form = GalleryForm()\r\n')
            fixed_lines.append('\r\n')
            fixed_lines.append('    if form.validate_on_submit():\r\n')
            fixed_lines.append('        # Handle image upload\r\n')
            fixed_lines.append('        image_path = None\r\n')
            fixed_lines.append('        if form.image.data:\r\n')
            fixed_lines.append('            image_path = save_file(form.image.data)\r\n')
            fixed_lines.append('\r\n')
            fixed_lines.append('        if not image_path:\r\n')
            fixed_lines.append('            flash(\'Please upload a valid image file\', \'danger\')\r\n')
            fixed_lines.append('            return redirect(url_for(\'admin.new_gallery_item\'))\r\n')
            fixed_lines.append('\r\n')
            fixed_lines.append('        # Create new gallery item\r\n')
            fixed_lines.append('        new_item = Gallery(\r\n')
            fixed_lines.append('            title=form.title.data,\r\n')
            fixed_lines.append('            description=form.description.data,\r\n')
            fixed_lines.append('            image=image_path,\r\n')
            fixed_lines.append('            featured=form.featured.data,\r\n')
            fixed_lines.append('            order_index=form.order_index.data or 0\r\n')
            fixed_lines.append('        )\r\n')
            fixed_lines.append('\r\n')
            fixed_lines.append('        # Map category string to GalleryCategory\r\n')
            fixed_lines.append('        category = GalleryCategory.query.filter_by(name=form.category.data).first()\r\n')
            fixed_lines.append('        if category:\r\n')
            fixed_lines.append('            new_item.category_id = category.id\r\n')
            fixed_lines.append('\r\n')
            fixed_lines.append('        db.session.add(new_item)\r\n')
            fixed_lines.append('        db.session.commit()\r\n')
            fixed_lines.append('\r\n')
            fixed_lines.append('        flash(\'Gallery item created successfully!\', \'success\')\r\n')
            fixed_lines.append('        return redirect(url_for(\'admin.gallery\'))\r\n')
            fixed_lines.append('\r\n')
            fixed_lines.append('    # Provide categories for the form selections\r\n')
            fixed_lines.append('    categories = GalleryCategory.query.all()\r\n')
            fixed_lines.append('    return render_template(\'admin/gallery/new.html\', form=form, categories=categories)\r\n')
            fixed_lines.append('\r\n')
            fixed_lines.append('@admin_bp.route(\'/gallery/edit/<int:gallery_id>\', methods=[\'GET\', \'POST\'])\r\n')
            fixed_lines.append('@login_required\r\n')
            fixed_lines.append('def edit_gallery_item(gallery_id):\r\n')
            fixed_lines.append('    from app import db\r\n')
            fixed_lines.append('    from models import GalleryCategory\r\n')
            fixed_lines.append('    gallery_item = Gallery.query.get_or_404(gallery_id)\r\n')
            fixed_lines.append('\r\n')
            fixed_lines.append('    if request.method == \'POST\':\r\n')
            fixed_lines.append('        gallery_item.title = request.form.get(\'title\')\r\n')
            fixed_lines.append('        gallery_item.description = request.form.get(\'description\')\r\n')
            fixed_lines.append('\r\n')
            fixed_lines.append('        # Update category by id if provided\r\n')
            fixed_lines.append('        category_id = request.form.get(\'category_id\')\r\n')
            fixed_lines.append('        if category_id:\r\n')
            fixed_lines.append('            category = GalleryCategory.query.get(category_id)\r\n')
            fixed_lines.append('            gallery_item.category_id = category.id if category else None\r\n')
            fixed_lines.append('\r\n')
            fixed_lines.append('        # Handle image upload if new image provided\r\n')
            fixed_lines.append('        if \'image\' in request.files and request.files[\'image\'].filename:\r\n')
            fixed_lines.append('            gallery_item.image = save_file(request.files[\'image\'])\r\n')
            fixed_lines.append('\r\n')
            fixed_lines.append('        db.session.commit()\r\n')
            fixed_lines.append('        flash(\'Gallery item updated successfully!\', \'success\')\r\n')
            fixed_lines.append('        return redirect(url_for(\'admin.gallery\'))\r\n')
            fixed_lines.append('\r\n')
            fixed_lines.append('    categories = GalleryCategory.query.all()\r\n')
            fixed_lines.append('    return render_template(\'admin/gallery_form.html\', item=gallery_item, categories=categories)\r\n')
            fixed_lines.append('\r\n')
            fixed_lines.append('@admin_bp.route(\'/gallery/delete/<int:gallery_id>\', methods=[\'POST\'])\r\n')
            fixed_lines.append('@login_required\r\n')
            fixed_lines.append('def delete_gallery_item(gallery_id):\r\n')
            fixed_lines.append('    gallery_item = Gallery.query.get_or_404(gallery_id)\r\n')
            fixed_lines.append('    \r\n')
            fixed_lines.append('    # Delete gallery image if it exists\r\n')
            fixed_lines.append('    if gallery_item.image:\r\n')
            fixed_lines.append('        try:\r\n')
            fixed_lines.append('            image_path = os.path.join(current_app.config[\'UPLOAD_FOLDER\'], gallery_item.image.split(\'/\')[-1])\r\n')
            fixed_lines.append('            if os.path.exists(image_path):\r\n')
            fixed_lines.append('                os.remove(image_path)\r\n')
            fixed_lines.append('        except Exception as e:\r\n')
            fixed_lines.append('            print(f\"Error deleting image: {e}\")\r\n')
            fixed_lines.append('    \r\n')
            fixed_lines.append('    db.session.delete(gallery_item)\r\n')
            fixed_lines.append('    db.session.commit()\r\n')
            fixed_lines.append('    \r\n')
            fixed_lines.append('    flash(\'Gallery item deleted successfully!\', \'success\')\r\n')
            fixed_lines.append('    return redirect(url_for(\'admin.gallery\'))\r\n')
            i += 6  # Skip lines 253-258
            continue
    
    # Fix 3: Lines 553-577 - Orphaned delete code in edit_blog_post
    elif line_num == 553 and '    if request.method == \'POST\':"' in lines[i]:
        # Check if this is the corrupted edit_blog_post section
        if i + 24 < len(lines) and 'Blog post deleted successfully' in lines[i + 24]:
            # Write the correct edit_blog_post function
            fixed_lines.append('    if request.method == \'POST\':\r\n')
            fixed_lines.append('        post.title = request.form.get(\'title\')\r\n')
            fixed_lines.append('        post.content = request.form.get(\'content\')\r\n')
            fixed_lines.append('        post.excerpt = request.form.get(\'excerpt\')\r\n')
            fixed_lines.append('        post.published = \'published\' in request.form\r\n')
            fixed_lines.append('        \r\n')
            fixed_lines.append('        # Update slug if title changed\r\n')
            fixed_lines.append('        if post.title != request.form.get(\'title\'):\r\n')
            fixed_lines.append('            post.slug = create_slug(request.form.get(\'title\'))\r\n')
            fixed_lines.append('        \r\n')
            fixed_lines.append('        # Handle image upload if new image provided\r\n')
            fixed_lines.append('        if \'image\' in request.files and request.files[\'image\'].filename:\r\n')
            fixed_lines.append('            post.image = save_file(request.files[\'image\'])\r\n')
            fixed_lines.append('        \r\n')
            fixed_lines.append('        db.session.commit()\r\n')
            fixed_lines.append('        flash(\'Blog post updated successfully!\', \'success\')\r\n')
            fixed_lines.append('        return redirect(url_for(\'admin.blog_posts\'))\r\n')
            fixed_lines.append('    \r\n')
            fixed_lines.append('    return render_template(\'admin/blog/edit.html\', post=post)\r\n')
            fixed_lines.append('\r\n')
            fixed_lines.append('@admin_bp.route(\'/blog/delete/<int:post_id>\', methods=[\'POST\'])\r\n')
            fixed_lines.append('@login_required\r\n')
            fixed_lines.append('def delete_blog_post(post_id):\r\n')
            fixed_lines.append('    post = BlogPost.query.get_or_404(post_id)\r\n')
            fixed_lines.append('    \r\n')
            fixed_lines.append('    # Delete post image if it exists\r\n')
            fixed_lines.append('    if post.image:\r\n')
            fixed_lines.append('        try:\r\n')
            fixed_lines.append('            image_path = os.path.join(current_app.config[\'UPLOAD_FOLDER\'], post.image.split(\'/\')[-1])\r\n')
            fixed_lines.append('            if os.path.exists(image_path):\r\n')
            fixed_lines.append('                os.remove(image_path)\r\n')
            fixed_lines.append('        except Exception as e:\r\n')
            fixed_lines.append('            print(f\"Error deleting image: {e}\")\r\n')
            fixed_lines.append('    \r\n')
            fixed_lines.append('    db.session.delete(post)\r\n')
            fixed_lines.append('    db.session.commit()\r\n')
            fixed_lines.append('    \r\n')
            fixed_lines.append('    flash(\'Blog post deleted successfully!\', \'success\')\r\n')
            fixed_lines.append('    return redirect(url_for(\'admin.blog_posts\'))\r\n')
            i += 25  # Skip lines 553-577
            continue
    
    # Keep the line as is
    fixed_lines.append(lines[i])
    i += 1

# Write the fixed file
with open(output_file, 'w', encoding='utf-8') as f:
    f.writelines(fixed_lines)

print(f"Fixed file written to: {output_file}")
print("Please review and replace the original file if correct.")
