"""Add missing fields and models for portfolio

Revision ID: 33d9367aead8
Revises: 
Create Date: 2025-07-30 14:08:29.878541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d9367aead8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gallery_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('project_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skill_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('blog_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('author_email', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['blog_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_post_tags',
    sa.Column('blog_post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blog_post.id'], name='fk_blog_post_tags_blog_post_id'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='fk_blog_post_tags_tag_id'),
    sa.PrimaryKeyConstraint('blog_post_id', 'tag_id')
    )
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reading_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=220),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_blog_post_category_id', 'blog_category', ['category_id'], ['id'])
        batch_op.drop_column('image')

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('replied', sa.Boolean(), nullable=True))

    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_gallery_category_id', 'gallery_category', ['category_id'], ['id'])
        batch_op.drop_column('category')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('short_description', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['slug'])
        batch_op.create_foreign_key('fk_project_category_id', 'project_category', ['category_id'], ['id'])

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_description', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('features', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=True))

    with op.batch_alter_table('site_visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referrer', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('visit_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=45),
               nullable=False)
        batch_op.alter_column('user_agent',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('page_visited',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('years_experience', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_skill_category_id', 'skill_category', ['category_id'], ['id'])
        batch_op.drop_column('category')

    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('client_company', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('testimonial_text', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('platform', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=True))
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('order_index')
        batch_op.drop_column('platform')
        batch_op.drop_column('testimonial_text')
        batch_op.drop_column('client_company')
        batch_op.drop_column('client_title')

    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')
        batch_op.drop_column('order_index')
        batch_op.drop_column('description')
        batch_op.drop_column('years_experience')

    with op.batch_alter_table('site_visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.alter_column('page_visited',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('user_agent',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('visit_date')
        batch_op.drop_column('referrer')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('order_index')
        batch_op.drop_column('price')
        batch_op.drop_column('features')
        batch_op.drop_column('short_description')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('category_id')
        batch_op.drop_column('order_index')
        batch_op.drop_column('short_description')
        batch_op.drop_column('slug')

    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')
        batch_op.drop_column('order_index')
        batch_op.drop_column('featured')

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('replied')
        batch_op.drop_column('subject')

    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('slug',
               existing_type=sa.String(length=220),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('category_id')
        batch_op.drop_column('reading_time')
        batch_op.drop_column('views')
        batch_op.drop_column('featured')
        batch_op.drop_column('featured_image')

    op.drop_table('blog_post_tags')
    op.drop_table('blog_comment')
    op.drop_table('tag')
    op.drop_table('skill_category')
    op.drop_table('project_category')
    op.drop_table('gallery_category')
    op.drop_table('blog_category')
    # ### end Alembic commands ###
