"""Add phone and email_verified to User model

Revision ID: 695b7a3b931a
Revises: 765b01c27e16
Create Date: 2025-08-27 17:11:06.177257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695b7a3b931a'
down_revision = '765b01c27e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
