"""Rename Analytics to Event and add session_id

Revision ID: 765b01c27e16
Revises: 59f22d00565d
Create Date: 2025-08-27 16:49:08.986646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765b01c27e16'
down_revision = '59f22d00565d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=128), nullable=True),
    sa.Column('site_description', sa.String(length=256), nullable=True),
    sa.Column('contact_email', sa.String(length=128), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('social_media_facebook', sa.String(length=256), nullable=True),
    sa.Column('social_media_twitter', sa.String(length=256), nullable=True),
    sa.Column('social_media_instagram', sa.String(length=256), nullable=True),
    sa.Column('social_media_linkedin', sa.String(length=256), nullable=True),
    sa.Column('google_analytics_id', sa.String(length=64), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('site_settings')
    op.drop_table('analytics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('meta', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.drop_table('event')
    op.drop_table('site_setting')
    # ### end Alembic commands ###
