"""add slug to blog_category

Revision ID: af043f1d2160
Revises: 33d9367aead8
Create Date: 2025-08-09 12:14:29.503923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af043f1d2160'
down_revision = '33d9367aead8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint('uq_blog_category_slug', ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_category', schema=None) as batch_op:
        batch_op.drop_constraint('uq_blog_category_slug', type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
